version: '3.8'

services:
  postgres:
    image: 'postgres:14-alpine'
    ports:
      - 5432:5432
    restart: always
    env_file:
      - ./.env
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    env_file:
      - ./.env
    depends_on:
      - postgres
    entrypoint: ['sh', '-c']
    command:
      - |
        npm run schema:sync
        npm run start:prod
